permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
# 作者信息
author: 
  name: kyu
  email: 13116075090@sina.cn
  link: http://Hikyu.github.io
  github: https://github.com/Hikyu
  wechat: 532411459
# 站点信息
title: kyu的博客
description: My personal blog
url: http://Hikyu.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/header.png
favicon: /public/img/header.png

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 工具

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  allarticle: 所有文章
  archive: 归档